= Hello CMake
:toc:
:toc-placement!:

toc::[]

# 简介

展示一个非常基础的hello world示例。

本教程目录下的文件结构如下：

```
A-hello-cmake$ tree
.
├── CMakeLists.txt
├── main.cpp
```

  * link:CMakeLists.txt[CMakeLists.txt] - 包含想要执行的CMake指令
  * link:main.cpp[main.cpp] - 一个简单的 "Hello World" cpp文件.

# 概念

### CMakeLists.txt

CMakeLists.txt里面保存有所有你的CMake指令。当在这个文件夹下运行cmake时，它将会搜索这个文件，如果没有找到则cmake将会退出并报错。

### 最低CMake版本指定

当采用CMake创建一个项目时，需要指定项目支持的最低的CMake版本。

[source,cmake]
----
cmake_minimum_required(VERSION 3.5)
----


### 项目

一个CMake构建可以包含一个项目名，以便在使用多个项目时可以很轻松地引用某些变量。

[source,cmake]
----
project (hello_cmake)
----


### 创建一个执行文件

+add_executable()+ 命令用来指定一个可执行文件，这个可执行文件是由指定的源文件构建而来（在本示例中是main.cpp）。+add_executable()+ 的第一个参数是需要构建的可执行文件名称，第二个参数是需要参与编译的源文件列表。

[source,cmake]
----
add_executable(hello_cmake main.cpp)
----


[NOTE]
====
有一个小技巧：如果想让项目名和可执行文件名相同，可以使用如下方式指定CMakeLists.txt文件。

[source,cmake]
----
cmake_minimum_required(VERSION 3.5)
project (hello_cmake)
add_executable(${PROJECT_NAME} main.cpp)
----

在这个示例中，+project()+ 函数将会创建一个值为hello_cmake的 +${PROJECT_NAME}+ 变量。这个变量可以传给 +add_executable()+ 函数来生成一个名为'hello_cmake'的可执行文件。
====


### 二进制目录

运行cmake命令的根文件夹或顶层文件夹被称为CMAKE_BINARY_DIR，这个文件夹是所有二进制文件的根文件夹。CMake支持两种构建和生成方式：内部构建（in-place build）和外部构建（out-of-source build），类似于Qt下的shadow build。


#### 内部构建（In-Place Build）

内部构建生成的所有临时构建文件都和源文件处于同一个目录下。这意味着所有的Makefiles和中间文件都穿插在普通的代码之中。要创建内部构建目标，可以在根目录下运行cmake命令：

[source,bash]
----
A-hello-cmake$ cmake .
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/matrim/workspace/cmake-examples/01-basic/A-hello-cmake

A-hello-cmake$ tree
.
├── CMakeCache.txt
├── CMakeFiles
│   ├── 2.8.12.2
│   │   ├── CMakeCCompiler.cmake
│   │   ├── CMakeCXXCompiler.cmake
│   │   ├── CMakeDetermineCompilerABI_C.bin
│   │   ├── CMakeDetermineCompilerABI_CXX.bin
│   │   ├── CMakeSystem.cmake
│   │   ├── CompilerIdC
│   │   │   ├── a.out
│   │   │   └── CMakeCCompilerId.c
│   │   └── CompilerIdCXX
│   │       ├── a.out
│   │       └── CMakeCXXCompilerId.cpp
│   ├── cmake.check_cache
│   ├── CMakeDirectoryInformation.cmake
│   ├── CMakeOutput.log
│   ├── CMakeTmp
│   ├── hello_cmake.dir
│   │   ├── build.make
│   │   ├── cmake_clean.cmake
│   │   ├── DependInfo.cmake
│   │   ├── depend.make
│   │   ├── flags.make
│   │   ├── link.txt
│   │   └── progress.make
│   ├── Makefile2
│   ├── Makefile.cmake
│   ├── progress.marks
│   └── TargetDirectories.txt
├── cmake_install.cmake
├── CMakeLists.txt
├── main.cpp
├── Makefile
----


#### 外部构建（Out-of-Source Build）

外部构建允许创建一个单独的构建文件夹，放置于系统中的任意位置。所有的临时构建、中间文件都位于这个文件夹下，有效保持源文件目录的整洁。要创建外部构建，可以新建一个build文件夹，之后在文件夹下运行cmake命令，并指定CMakeLists.txt文件所在的路径。
使用外部构建还有一个好处：当你想重新由源文件生成cmake环境，你只需要删除构建文件加下的所有文件并重新运行cmake即可。

[source,bash]
----
A-hello-cmake$ mkdir build

A-hello-cmake$ cd build/

A-hello-cmake/build$ make ..
make: Nothing to be done for `..'.
matrim@freyr:~/workspace/cmake-examples/01-basic/A-hello-cmake/build$ cmake ..
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/matrim/workspace/cmake-examples/01-basic/A-hello-cmake/build

A-hello-cmake/build$ cd ..

A-hello-cmake$ tree
.
├── build
│   ├── CMakeCache.txt
│   ├── CMakeFiles
│   │   ├── 2.8.12.2
│   │   │   ├── CMakeCCompiler.cmake
│   │   │   ├── CMakeCXXCompiler.cmake
│   │   │   ├── CMakeDetermineCompilerABI_C.bin
│   │   │   ├── CMakeDetermineCompilerABI_CXX.bin
│   │   │   ├── CMakeSystem.cmake
│   │   │   ├── CompilerIdC
│   │   │   │   ├── a.out
│   │   │   │   └── CMakeCCompilerId.c
│   │   │   └── CompilerIdCXX
│   │   │       ├── a.out
│   │   │       └── CMakeCXXCompilerId.cpp
│   │   ├── cmake.check_cache
│   │   ├── CMakeDirectoryInformation.cmake
│   │   ├── CMakeOutput.log
│   │   ├── CMakeTmp
│   │   ├── hello_cmake.dir
│   │   │   ├── build.make
│   │   │   ├── cmake_clean.cmake
│   │   │   ├── DependInfo.cmake
│   │   │   ├── depend.make
│   │   │   ├── flags.make
│   │   │   ├── link.txt
│   │   │   └── progress.make
│   │   ├── Makefile2
│   │   ├── Makefile.cmake
│   │   ├── progress.marks
│   │   └── TargetDirectories.txt
│   ├── cmake_install.cmake
│   └── Makefile
├── CMakeLists.txt
├── main.cpp
----

教程中的所有示例都将采用外部构建方式构建。


# 构建示例

下面是构建这个示例的输出。

[source,bash]
----
$ mkdir build

$ cd build

$ cmake ..
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Configuring done
-- Generating done
-- Build files have been written to: /workspace/cmake-examples/01-basic/hello_cmake/build

$ make
Scanning dependencies of target hello_cmake
[100%] Building CXX object CMakeFiles/hello_cmake.dir/hello_cmake.cpp.o
Linking CXX executable hello_cmake
[100%] Built target hello_cmake

$ ./hello_cmake
Hello CMake!
----
