= Building with ninja
:toc:
:toc-placement!:

toc::[]

# 简介

正如之前所述，CMake是一个元构建系统(meta-build system)，可以用来创建其他构建工具所需的构建文件。这个示例展示了如何通过CMake来使用 https://ninja-build.org/[ninja build] 构建。

教程中的文件结构如下：

```
$ tree
.
├── CMakeLists.txt
├── main.cpp
```

  * link:CMakeLists.txt[] - 包含需要运行的CMake命令
  * link:main.cpp[] - 一个简单"Hello World"源文件

# 概念

### 生成器

CMake的 https://cmake.org/cmake/help/v3.0/manual/cmake-generators.7.html[生成器(generators)] 负责为选定的构建系统生成输入文件。
运行 `cmake --help` 可以查看当前平台下支持的生成器。对于cmake v2.8.12.2，在linux下支持的生成器包括：

[source,bash]
----
Generators

The following generators are available on this platform:
  Unix Makefiles              = Generates standard UNIX makefiles.
  Ninja                       = Generates build.ninja files (experimental).
  CodeBlocks - Ninja          = Generates CodeBlocks project files.
  CodeBlocks - Unix Makefiles = Generates CodeBlocks project files.
  Eclipse CDT4 - Ninja        = Generates Eclipse CDT 4.0 project files.
  Eclipse CDT4 - Unix Makefiles
                              = Generates Eclipse CDT 4.0 project files.
  KDevelop3                   = Generates KDevelop 3 project files.
  KDevelop3 - Unix Makefiles  = Generates KDevelop 3 project files.
  Sublime Text 2 - Ninja      = Generates Sublime Text 2 project files.
  Sublime Text 2 - Unix Makefiles
                              = Generates Sublime Text 2 project files.Generators
----

如这篇 https://stackoverflow.com/questions/25941536/what-is-a-cmake-generator[文章] 提及的，CMake包括了多种不同类型的生成器，包括命令行、IDE和其他生成器。

#### 命令行构建生成器

这些生成器适用于命令行构建工具，例如Make和Ninja。在使用CMake生成构建系统之前，必须对所选的工具链进行配置。

所支持的生成器包括：

  * Borland Makefiles
  * MSYS Makefiles
  * MinGW Makefiles
  * NMake Makefiles
  * NMake Makefiles JOM
  * Ninja
  * Unix Makefiles
  * Watcom WMake

#### IDE构建生成器

这些生成器适用于集成开发环境（IDE）及其对应的编译器。例如Visual Studio和Xcode，它们本身就包含一个编译器。

所支持的生成器包括：

  * Visual Studio 6
  * Visual Studio 7
  * Visual Studio 7 .NET 2003
  * Visual Studio 8 2005
  * Visual Studio 9 2008
  * Visual Studio 10 2010
  * Visual Studio 11 2012
  * Visual Studio 12 2013
  * Xcode

#### 其他生成器

这些生成器会创建一份配置来使用另一个IDE工具，并且必须被IDE或者命令行生成器所包含。

The supported generators include:

 * CodeBlocks
 * CodeLite
 * Eclipse CDT4
 * KDevelop3
 * Kate
 * Sublime Text 2


[NOTE]
====
在本示例中，ninja利用命令行安装 `sudo apt-get install ninja-build`
====

### 调用一个生成器

可以使用 `G` 命令来切换CMake生成器，例如：

[source,cmake]
----
cmake .. -G Ninja
----

运行上面指令后，CMake将生成所需的Ninja构建文件，可以通过`ninja` 命令来运行。
After doing the above CMake will generate the required Ninja build files, which can be run
from using the `ninja` command.

[source,bash]
----
$ cmake .. -G Ninja

$ ls
build.ninja  CMakeCache.txt  CMakeFiles  cmake_install.cmake  rules.ninja
----

# 构建示例

如下是构建示例时的输出：

[source,bash]
----
$ mkdir build.ninja

$ cd build.ninja/

$ cmake .. -G Ninja
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler using: Ninja
-- Check for working C compiler using: Ninja -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler using: Ninja
-- Check for working CXX compiler using: Ninja -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/matrim/workspace/cmake-examples/01-basic/J-building-with-ninja/build.ninja

$ ninja -v
[1/2] /usr/bin/c++     -MMD -MT CMakeFiles/hello_cmake.dir/main.cpp.o -MF "CMakeFiles/hello_cmake.dir/main.cpp.o.d" -o CMakeFiles/hello_cmake.dir/main.cpp.o -c ../main.cpp
[2/2] : && /usr/bin/c++      CMakeFiles/hello_cmake.dir/main.cpp.o  -o hello_cmake  -rdynamic && :

$ ls
build.ninja  CMakeCache.txt  CMakeFiles  cmake_install.cmake  hello_cmake  rules.ninja

$ ./hello_cmake
Hello CMake!
----
