= Installing
:toc:
:toc-placement!:

toc::[]

# Introduction

本示例展示了如何创建一个`make install`目标，用来在系统中安装普通文件和二进制文件。本示例基于上一个共享库示例开发。

教程中的文件结构如下：

```
$ tree
.
├── cmake-examples.conf
├── CMakeLists.txt
├── include
│   └── installing
│       └── Hello.h
├── README.adoc
└── src
    ├── Hello.cpp
    └── main.cpp
```

  * link:CMakeLists.txt[] - 包含要运行的CMake命令
  * link:cmake-examples.conf[] - 示例配置文件
  * link:include/installing/Hello.h[] - 需要包含的头文件
  * link:src/Hello.cpp[] - 需要编译的源文件
  * link:src/main.cpp[] - 需要参与编译的源文件（包含main函数）

# 概念

## 安装

CMake通过创建`make install`目标来使用户可以安装二进制文件、库文件和其他文件。安装位置的起始位置由变量 +CMAKE_INSTALL_PREFIX+ 控制，
可以通过ccmake（带界面的cmake，用cmake-gui也行）或者在运行cmake时添加选项 `cmake .. -DCMAKE_INSTALL_PREFIX=/install/location` 来实现。

文件的安装通过 https://cmake.org/cmake/help/v3.0/command/install.html[+install()+] 函数控制。

[source,cmake]
----
install (TARGETS cmake_examples_inst_bin
    DESTINATION bin)
----

将add_executable生成的可执行文件cmake_examples_inst_bin安装到目标位置 +${CMAKE_INSTALL_PREFIX}/bin+

[source,cmake]
----
install (TARGETS cmake_examples_inst
    LIBRARY DESTINATION lib)
----

将add_library生成的共享库cmake_examples_inst安装到目标位置 +${CMAKE_INSTALL_PREFIX}/lib+

[NOTE]
====
这在Windows下可能失效。在产生DLL目标的平台上安装时，需要添加以下命令：

[source,cmake]
----
install (TARGETS cmake_examples_inst
    LIBRARY DESTINATION lib
    RUNTIME DESTINATION bin)
----
====


[source,cmake]
----
install(DIRECTORY ${PROJECT_SOURCE_DIR}/include/ 
    DESTINATION include)
----

安装开发 +cmake_examples_inst+ 共享库所需的头文件到指定位置 +${CMAKE_INSTALL_PREFIX}/include+。

[source,cmake]
----
install (FILES cmake-examples.conf
    DESTINATION etc)
----

安装配置文件到目标位置 +${CMAKE_INSTALL_PREFIX}/etc+

在执行`make install`后，CMake将产生一个install_manifest.txt文件，其中包含了安装文件的详细信息。

[NOTE]
====
如果以超级用户root运行`make install`命令，则install_manifest.txt文件的所有者为root。
====

# 构建示例

[source,bash]
----
$ mkdir build

$ cd build/

$ cmake ..
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/matrim/workspace/cmake-examples/01-basic/E-installing/build

$ make
Scanning dependencies of target cmake_examples_inst
[ 50%] Building CXX object CMakeFiles/cmake_examples_inst.dir/src/Hello.cpp.o
Linking CXX shared library libcmake_examples_inst.so
[ 50%] Built target cmake_examples_inst
Scanning dependencies of target cmake_examples_inst_bin
[100%] Building CXX object CMakeFiles/cmake_examples_inst_bin.dir/src/main.cpp.o
Linking CXX executable cmake_examples_inst_bin
[100%] Built target cmake_examples_inst_bin

$ sudo make install
[sudo] password for matrim:
[ 50%] Built target cmake_examples_inst
[100%] Built target cmake_examples_inst_bin
Install the project...
-- Install configuration: ""
-- Installing: /usr/local/bin/cmake_examples_inst_bin
-- Removed runtime path from "/usr/local/bin/cmake_examples_inst_bin"
-- Installing: /usr/local/lib/libcmake_examples_inst.so
-- Installing: /usr/local/etc/cmake-examples.conf

$ cat install_manifest.txt
/usr/local/bin/cmake_examples_inst_bin
/usr/local/lib/libcmake_examples_inst.so
/usr/local/etc/cmake-examples.conf

$ ls /usr/local/bin/
cmake_examples_inst_bin

$ ls /usr/local/lib
libcmake_examples_inst.so

$ ls /usr/local/etc/
cmake-examples.conf

$ LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib cmake_examples_inst_bin
Hello Install!
----

[NOTE]
====
如果`/usr/local/lib`不在你的库目录下，则需要在运行可执行文件之前将其添加到路径中。
====

[[extra-notes]]
Extra Notes
~~~~~~~~~~~

[[default-location]]
Overriding the default install location
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

安装路径的起始位置 +CMAKE_INSTALL_PERFIX+ 的默认值为`/usr/local/`

如果想要为所有用户改变默认安装路径，可以在加入可执行文件或库前，在顶层CMakeLists.txt文件中加入如下代码：

[source,cmake]
----
if( CMAKE_INSTALL_PREFIX_INITIALIZED_TO_DEFAULT )
  message(STATUS "Setting default CMAKE_INSTALL_PREFIX path to ${CMAKE_BINARY_DIR}/install")
  set(CMAKE_INSTALL_PREFIX "${CMAKE_BINARY_DIR}/install" CACHE STRING "The path to use for make install" FORCE)
endif()
----

这个示例将默认安装路径设置到了你的构建目录下。

[[destdir]]
DESTDIR
^^^^^^^

如果想要把安装文件暂存起来，以便于确认是否所有的目标都被包含在`make install`之中，可以利用DESTDIR参数。
（其实就是把${CMAKE_INSTALL_PREFIX}再放到统一的文件夹下）

```
make install DESTDIR=/tmp/stage
```

这将会为所有安装文件创建一个安装路径`${DESTDIR}/${CMAKE_INSTALL_PREFIX}`。在这个示例中，所有的文件都将安装到`/tmp/stage/usr/local`下。

```
$ tree /tmp/stage
/tmp/stage
└── usr
    └── local
        ├── bin
        │   └── cmake_examples_inst_bin
        ├── etc
        │   └── cmake-examples.conf
        └── lib
            └── libcmake_examples_inst.so
```

[[uninstall]]
Uninstall
^^^^^^^^^

默认情况下CMake没有添加`make uninstall`目标。如何生成uninstall目标可以参考 https://cmake.org/Wiki/CMake_FAQ#Can_I_do_.22make_uninstall.22_with_CMake.3F[FAQ]

一个移除本示例所有安装文件的简单方式，可以使用：

```
sudo xargs rm < install_manifest.txt
```
