= Hello Headers
:toc:
:toc-placement!:

toc::[]


# 简介

展示一个hello world示例，采用不同的文件夹存放源文件和包含文件（头文件）。

教程下的文件结构如下：

```
B-hello-headers$ tree
.
├── CMakeLists.txt
├── include
│   └── Hello.h
└── src
    ├── Hello.cpp
    └── main.cpp
```

  * link:CMakeLists.txt[CMakeLists.txt] - 包含要运行的CMake命令。
  * link:include/Hello.h[include/Hello.h] - 需要包含的头文件。
  * link:src/Hello.cpp[src/Hello.cpp] - 需要参与编译的源文件。
  * link:src/main.cpp[src/main.cpp] - 需要参与编译的源文件（包含main函数）。


# 概念

## 目录路径

CMake语法指定了一系列 https://cmake.org/Wiki/CMake_Useful_Variables[变量] ，用于快速定位到项目中有用的目录。
其中一些包括：

[cols=",",options="header",]
|=======================================================================
|变量 |信息
|CMAKE_SOURCE_DIR |源文件根目录

|CMAKE_CURRENT_SOURCE_DIR |当前源文件目录（如果使用子项目或目录情况下）

|PROJECT_SOURCE_DIR |当前cmake项目的源文件目录

|CMAKE_BINARY_DIR |二进制/构建根目录，这个目录是运行cmake命令的目录

|CMAKE_CURRENT_BINARY_DIR |当前所在的构建目录

|PROJECT_BINARY_DIR |当前项目的构建目录
|=======================================================================

## 源文件变量

创建一个包含源文件的变量，这个变量可以清晰展示源文件并轻松地添加到多个指定当中，比如可以在 +add_executable()+ 中使用。

[source,cmake]
----
# Create a sources variable with a link to all cpp files to compile
set(SOURCES
    src/Hello.cpp
    src/main.cpp
)

add_executable(${PROJECT_NAME} ${SOURCES})
----

[NOTE]
====
另一种为 +SOURCES+ 变量指定文件名的方法是利用GLOB命令，使用通配符模式查到符合的文件。

[source,cmake]
----
file(GLOB SOURCES "src/*.cpp")
----
====


[TIP]
====
对于现代CMake来说，不建议为源文件设置变量，取而代之的是直接在add_xxx函数中声明源文件。

这对于GLOB命令尤为重要，因为如果使用GLOB命令添加新的源文件，不一定总是能显示正确的结果。
====

## 包含目录

如果存在不同的包含文件夹，你可以利用 +target_include_directories()+ link:https://cmake.org/cmake/help/v3.0/command/target_include_directories.html[命令] 来让编译器找到他们。当编译这个目标时，会将这些目录作为-I选项添加到编译器，例如`-I/directory/path`

[source,cmake]
----
target_include_directories(target
    PRIVATE 
        ${PROJECT_SOURCE_DIR}/include
)
----

+PRIVATE+ 标识符指定了包含文件的使用范围。这对于库的使用时很重要的，将在下一个示例中进行解释。更多细节可以参见link:https://cmake.org/cmake/help/v3.0/command/target_include_directories.html[这里]

# 构建示例

## 标准输出

构建这个示例的标准输出如下：

[source,bash]
----
$ mkdir build

$ cd build

$ cmake ..
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/matrim/workspace/cmake-examples/01-basic/hello_headers/build

$ make
Scanning dependencies of target hello_headers
[ 50%] Building CXX object CMakeFiles/hello_headers.dir/src/Hello.cpp.o
[100%] Building CXX object CMakeFiles/hello_headers.dir/src/main.cpp.o
Linking CXX executable hello_headers
[100%] Built target hello_headers

$ ./hello_headers
Hello Headers!
----


## 详细输出

在之前的示例中，当运行make命令时，输出信息只显示构建状态。为了展示全部输出，以便于调试，可以在运行make时添加 +VERBOSE=1+ 标志。

详细输出如下所示，从输出中可以看出，包含目录通过-I选项，在编译时被传递给编译器。

[source,bash]
----
$ make clean

$ make VERBOSE=1
/usr/bin/cmake -H/home/matrim/workspace/cmake-examples/01-basic/hello_headers -B/home/matrim/workspace/cmake-examples/01-basic/hello_headers/build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /home/matrim/workspace/cmake-examples/01-basic/hello_headers/build/CMakeFiles /home/matrim/workspace/cmake-examples/01-basic/hello_headers/build/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make[1]: Entering directory `/home/matrim/workspace/cmake-examples/01-basic/hello_headers/build'
make -f CMakeFiles/hello_headers.dir/build.make CMakeFiles/hello_headers.dir/depend
make[2]: Entering directory `/home/matrim/workspace/cmake-examples/01-basic/hello_headers/build'
cd /home/matrim/workspace/cmake-examples/01-basic/hello_headers/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/matrim/workspace/cmake-examples/01-basic/hello_headers /home/matrim/workspace/cmake-examples/01-basic/hello_headers /home/matrim/workspace/cmake-examples/01-basic/hello_headers/build /home/matrim/workspace/cmake-examples/01-basic/hello_headers/build /home/matrim/workspace/cmake-examples/01-basic/hello_headers/build/CMakeFiles/hello_headers.dir/DependInfo.cmake --color=
make[2]: Leaving directory `/home/matrim/workspace/cmake-examples/01-basic/hello_headers/build'
make -f CMakeFiles/hello_headers.dir/build.make CMakeFiles/hello_headers.dir/build
make[2]: Entering directory `/home/matrim/workspace/cmake-examples/01-basic/hello_headers/build'
/usr/bin/cmake -E cmake_progress_report /home/matrim/workspace/cmake-examples/01-basic/hello_headers/build/CMakeFiles 1
[ 50%] Building CXX object CMakeFiles/hello_headers.dir/src/Hello.cpp.o
/usr/bin/c++    -I/home/matrim/workspace/cmake-examples/01-basic/hello_headers/include    -o CMakeFiles/hello_headers.dir/src/Hello.cpp.o -c /home/matrim/workspace/cmake-examples/01-basic/hello_headers/src/Hello.cpp
/usr/bin/cmake -E cmake_progress_report /home/matrim/workspace/cmake-examples/01-basic/hello_headers/build/CMakeFiles 2
[100%] Building CXX object CMakeFiles/hello_headers.dir/src/main.cpp.o
/usr/bin/c++    -I/home/matrim/workspace/cmake-examples/01-basic/hello_headers/include    -o CMakeFiles/hello_headers.dir/src/main.cpp.o -c /home/matrim/workspace/cmake-examples/01-basic/hello_headers/src/main.cpp
Linking CXX executable hello_headers
/usr/bin/cmake -E cmake_link_script CMakeFiles/hello_headers.dir/link.txt --verbose=1
/usr/bin/c++       CMakeFiles/hello_headers.dir/src/Hello.cpp.o CMakeFiles/hello_headers.dir/src/main.cpp.o  -o hello_headers -rdynamic
make[2]: Leaving directory `/home/matrim/workspace/cmake-examples/01-basic/hello_headers/build'
/usr/bin/cmake -E cmake_progress_report /home/matrim/workspace/cmake-examples/01-basic/hello_headers/build/CMakeFiles  1 2
[100%] Built target hello_headers
make[1]: Leaving directory `/home/matrim/workspace/cmake-examples/01-basic/hello_headers/build'
/usr/bin/cmake -E cmake_progress_start /home/matrim/workspace/cmake-examples/01-basic/hello_headers/build/CMakeFiles 0
----
