= Static Library
:toc:
:toc-placement!:

toc::[]

# 简介

展示一个hello world示例，该示例首先创建并链接一个静态库。这是一个简化示例，展示了库和二进制在同一个文件夹下。这在子项目中经常出现，这将在 link:../../02-sub-projects[02-sub-projects] 项目中详细介绍。

教程中的文件结构如下：

```
$ tree
.
├── CMakeLists.txt
├── include
│   └── static
│       └── Hello.h
└── src
    ├── Hello.cpp
    └── main.cpp
```

  * link:CMakeLists.txt[] - 包含要运行的CMake命令
  * link:include/static/Hello.h[] - 包含的头文件
  * link:src/Hello.cpp[] - 需要编译的源文件
  * link:src/main.cpp[] - 需要参与编译的源文件（包含main函数）


# 概念

## 添加一个静态库

+add_library()+ 函数用于从源文件创建链接库。
调用方式如下：

[source,cmake]
----
add_library(hello_library STATIC 
    src/Hello.cpp
)
----

这将会创建一个名为libhello_library.a的静态库（STATIC）。

[NOTE]
====
如上一个示例所示，我们直接将源文件传入 +add_library+ 中，正如现代CMake推荐的用法一样。
====

## 包含目录

在本例中，我们使用 +target_include_directories()+ 函数在链接库库中包含目录，其作用域设置为 +PUBLIC+ 。

[source,cmake]
----
target_include_directories(hello_library
    PUBLIC 
        ${PROJECT_SOURCE_DIR}/include
)
----

这将会使包含目录可以在一下位置使用：
This will cause the included directory used in the following places:

* 当编译链接库时
* 当编译任何链接到这个库的其他目标时

作用域范围的含义如下：

* +PRIVATE+ - 添加目录到目标的包含目录中
* +INTERFACE+ - 添加目录到任何链接到这个库的其他目标的包含目录中
* +PUBLIC+ - As above, it is included in this library and also any targets that link this library.同上， 添加目录到此库以及任何链接到此库的其他目标中


[TIP]
====

对于公共头文件来说，推荐在包含文件夹下建立子目录作为“命名空间”。

传入 +target_include_directories+ 的目录是包含目录的根目录，C++源文件应该包含从根目录开始到其所需头文件的相对路径。

对于本例来说，在hello.cpp文件中包含头文件时格式如下：
[source,cpp]
----
#include "static/Hello.h"
----

采用这种方法可以避免头文件的命名冲突，从而可以在项目中使用多个链接库。
====

## 链接一个库

当创建一个需要调用这个链接库的可执行文件时，必须要告诉编译器需要使用的链接库。可以使用 +target_link_library()+ 函数来实现。

[source,cmake]
----
add_executable(hello_binary 
    src/main.cpp
)

target_link_libraries( hello_binary
    PRIVATE  
        hello_library
)
----

这个函数会告知CMake在链接期间将hello_library链接到可执行文件hello_binary上。函数还将从链接的库目标开始，传播具有 +PUBLIC+ 或+INTERFACE+ 作用域的包含目录。

编译器调用它的一个例子：

```
/usr/bin/c++ CMakeFiles/hello_binary.dir/src/main.cpp.o -o hello_binary -rdynamic libhello_library.a
```


# 构建示例

[source,bash]
----
$ mkdir build

$ cd build

$ cmake ..
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/matrim/workspace/cmake-examples/01-basic/C-static-library/build

$ make
Scanning dependencies of target hello_library
[ 50%] Building CXX object CMakeFiles/hello_library.dir/src/Hello.cpp.o
Linking CXX static library libhello_library.a
[ 50%] Built target hello_library
Scanning dependencies of target hello_binary
[100%] Building CXX object CMakeFiles/hello_binary.dir/src/main.cpp.o
Linking CXX executable hello_binary
[100%] Built target hello_binary

$ ls
CMakeCache.txt  CMakeFiles  cmake_install.cmake  hello_binary  libhello_library.a  Makefile

$ ./hello_binary
Hello Static Library!
----
