= Including Third Party Library
:toc:
:toc-placement!:

toc::[]

# 简介

几乎所有重要的项目都需要包含第三方的库、头文件以及程序。CMake可以利用 `find_package()` 函数来搜索这些第三方工具的路径。这个函数将会从`CMAKE_MODULE_PATH`中所列出的文件夹中寻找格式为"FindXXX.cmake"的CMake模块。在Linux中，默认的搜索路径包括`/usr/share/cmake/Modules`。在我的系统中，包含了大概142个常用的第三方库的支持。

教程的文件结构如下：

```
$ tree
.
├── CMakeLists.txt
├── main.cpp
```

  * link:CMakeLists.txt[] - 包含要运行的CMake指令
  * link:main.cpp[] - 需要参与编译的源文件（包含main函数）

# 需求

这个示例需要在默认位置安装boost库。

$ sudo apt-get install libboost-all-dev

# 概念

## 寻找一个功能包

如上所述，`find_package()` 函数将会从`CMAKE_MODULE_PATH`中所列出的文件夹中寻找格式为"FindXXX.cmake"的CMake模块。`find_package()` 中所需的参数格式由所需的模块决定，这通常记录在 `FindXXX.cmake` 文件的顶部。

一个寻找boost的简单示例如下：

[source,cmake]
----
find_package(Boost 1.46.1 REQUIRED COMPONENTS filesystem system)
----

The arguments are:

  * Boost - 库名称，这是要寻找的模块名称FindBoost.cmake的一部分
  * 1.46.1 - 所需boost库的最低版本
  * REQUIRED - 告知CMake这个模块使必须的，如果找不到就提示失败
  * COMPONENTS - 要查找的库列表（Boost是一个库集合，用COMPONENTS指定具体查找的子库）

Boost的引入可以接收更多参数，并且可以使用其他变量。后面的示例提供了更复杂的配置。


## 检查功能包是否找到

大多数引入的功能包将会设置变量 `XXX_FOUND`，用来检查功能包是否可用。

在本示例中，这个变量是 `Boost_FOUND`：

[source,cmake]
----
if(Boost_FOUND)
    message ("boost found")
    include_directories(${Boost_INCLUDE_DIRS})
else()
    message (FATAL_ERROR "Cannot find Boost")
endif()
----

## 导出变量

当功能包被找到后，会导出变量来通知用户其中的库、头文件以及可执行文件的位置。类似于 `XXX_FOUND` 变量，这些变量特定于功能包，通常记录在 `FindXXX.cmake` 文件的顶部。

本示例中导出变量包括：

  * `Boost_INCLUDE_DIRS` - boost的头文件路径。

在某些条件下，可以通过ccmake或者cmake-gui检查cache来检查这些变量。

## 别名/导入目标

大多数现代CMake库在其模块文件中 link:https://cmake.org/cmake/help/v3.6/prop_tgt/IMPORTED.html#prop_tgt:IMPORTED[导出（export）] +别名（ALIAS）+ 目标。

导入目标的优势是，可以同事填充包含目录和链接库。

举例来说，Boost模块从v3.5+版本的CMake开始支持别名/导入目标。类似于使用自定义的ALIAS目标（`add_library(hello::library ALIAS hello_library)`），模块中的 +ALIAS+ 可以使查找目标更加容易。

在Boost中，所有目标在导出时都加入了`Boost::`标识符，后面紧跟子系统的名称。例如：

  * `Boost::boost` for header only libraries
  * `Boost::system` for the boost system library.
  * `Boost::filesystem` for filesystem library.

与自己定义的目标一样，这个目标也包含他们的依赖，因此当链接到 `Boost::filesystem` 时将会自动添加 `Boost::boost` and `Boost::system` 依赖。

为了链接到导入目标，可以使用如下方式（感觉方便之处是不用手动添加各种头文件和库的变量）：

[source,cmake]
----
  target_link_libraries( third_party_include
      PRIVATE
          Boost::filesystem
  )
----

## 无别名目标

尽管绝大多数现代库都采用了导入目标，但并不是所有模块都更新了。在一些库并未更新的情况下，将会找到如下变量：

  * xxx_INCLUDE_DIRS - 指向库包含路径的变量
  * xxx_LIBRARY - 指向库路径的变量

添加变量到 +target_include_directories+ 和 +target_link_libraries+ 中：

[source,cmake]
----
# Include the boost headers
target_include_directories( third_party_include
    PRIVATE ${Boost_INCLUDE_DIRS}
)

# link against the boost libraries
target_link_libraries( third_party_include
    PRIVATE
    ${Boost_SYSTEM_LIBRARY}
    ${Boost_FILESYSTEM_LIBRARY}
)
----

# 构建示例

[source,bash]
----
$ mkdir build

$ cd build/

$ cmake ..
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   filesystem
--   system
boost found
-- Configuring done
-- Generating done
-- Build files have been written to: /home/matrim/workspace/cmake-examples/01-basic/H-third-party-library/build

$ make
Scanning dependencies of target third_party_include
[100%] Building CXX object CMakeFiles/third_party_include.dir/main.cpp.o
Linking CXX executable third_party_include
[100%] Built target third_party_include
matrim@freyr:~/workspace/cmake-examples/01-basic/H-third-party-library/build$ ./
CMakeFiles/          third_party_include
matrim@freyr:~/workspace/cmake-examples/01-basic/H-third-party-library/build$ ./third_party_include
Hello Third Party Include!
Path is not relative
$ cmake ..
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   filesystem
--   system
boost found
-- Configuring done
-- Generating done
-- Build files have been written to: /home/matrim/workspace/cmake-examples/01-basic/H-third-party-library/build

$ make
Scanning dependencies of target third_party_include
[100%] Building CXX object CMakeFiles/third_party_include.dir/main.cpp.o
Linking CXX executable third_party_include
[100%] Built target third_party_include

$ ./third_party_include
Hello Third Party Include!
Path is not relative

----
