= Basic Sub-Project
:toc:
:toc-placement!:

toc::[]

# 简介

这个示例展示了如何设置一个包含子项目的CMake项目。顶层的CMakeLists.txt通过调用子目录下的CMakeLists.txt文件生成如下：

  * sublibrary1 - 一个静态库
  * sublibrary2 - 一个仅有头文件的库
  * subbinary - 一个可执行文件

教程中的文件结构如下：

```
$ tree
.
├── CMakeLists.txt
├── subbinary
│   ├── CMakeLists.txt
│   └── main.cpp
├── sublibrary1
│   ├── CMakeLists.txt
│   ├── include
│   │   └── sublib1
│   │       └── sublib1.h
│   └── src
│       └── sublib1.cpp
└── sublibrary2
    ├── CMakeLists.txt
    └── include
        └── sublib2
            └── sublib2.h
```

  * link:CMakeLists.txt[] - 顶层的CMakeLists.txt
  * link:subbinary/CMakeLists.txt[] - 用于编译可执行文件
  * link:subbinary/main.cpp[] - 可执行文件源文件
  * link:sublibrary1/CMakeLists.txt[] - 用于编译静态库
  * link:sublibrary1/include/sublib1/sublib1.h[]
  * link:sublibrary1/src/sublib1.cpp[]
  * link:sublibrary2/CMakeLists.txt[] - 用于设置仅有头文件的库
  * link:sublibrary2/include/sublib2/sublib2.h[]

[TIP]
====
在本示例中，将所有的头文件都放置在每一个项目对应的 +include+ 文件夹下的子文件夹中，而将目标的include保留为根目录下的 +include+ 文件夹。 这是一个避免文件名冲突很好的方法，因此你必须使用如下方式包含头文件：
[source,cpp]
----
#include "sublib1/sublib1.h"
----

这同样意味着当你将你的库安装到其他用户时，默认安装位置为
+/usr/local/include/sublib1/sublib1.h+.
====

# 概念

## 添加一个子目录

一个CMakeLists.txt文件可以包含并调用包含CmakeLists.txt的子目录。

[source,cmake]
----
add_subdirectory(sublibrary1)
add_subdirectory(sublibrary2)
add_subdirectory(subbinary)
----

## 引用子项目目录

当使用 `project()` 的命令创建项目时， CMake将同时自动创建许多跟项目信息相关的变量。这些变量可以被主项目或其他子项目使用。举例来说，为了引用不同项目的源文件目录，可以使用如下变量：

[source,cmake]
----
    ${sublibrary1_SOURCE_DIR}
    ${sublibrary2_SOURCE_DIR}
----

CMake创建的变量包括：

[cols=",",options="header",]
|=======================================================================
| 变量 | 信息
|PROJECT_NAME | 由当前`project()`产生的项目名称.

|CMAKE_PROJECT_NAME | 由第一个项目 `project()` 设置的项目名称，例如顶层的项目

|PROJECT_SOURCE_DIR | 当前项目的源目录

|PROJECT_BINARY_DIR | 当前项目的构建目录

|name_SOURCE_DIR | 名叫"name"的项目的源目录。在本示例中创建的源目录包括 `sublibrary1_SOURCE_DIR`，`sublibrary2_SOURCE_DIR` 和 `subbinary_SOURCE_DIR`

|name_BINARY_DIR | 名叫"name"的项目的构建目录。在本示例中创建的源目录包括`sublibrary1_BINARY_DIR`，
`sublibrary2_BINARY_DIR` 和 `subbinary_BINARY_DIR`

|=======================================================================

## 头文件库

如果有一个头文件库， cmake提供 +INTERFACE+ 目标来创建一个不包含任何构建输出的目标。跟多细节可以查看 link:https://cmake.org/cmake/help/v3.4/command/add_library.html#interface-libraries[here]

[source,cmake]
----
add_library(${PROJECT_NAME} INTERFACE)
----

在创建目标时，还可以使用 +INTERFACE+ 作用域来包含目录。+INTERFACE+ 作用域用于生成可以在任何链接到该目标的库中使用的目标依赖，但不在目标本身的编译中。

[source,cmake]
----
target_include_directories(${PROJECT_NAME}
    INTERFACE
        ${PROJECT_SOURCE_DIR}/include
)
----

## 从子项目引用库

如果子项目创建一个库，那么这个库可以被其他项目所引用，通过在 `target_link_libraries()` 调用项目名称。这意味着您不必引用新库的完整路径，同时还可以将其作为依赖项添加。

[source,cmake]
----
target_link_libraries(subbinary
    PUBLIC
        sublibrary1
)
----

或者，可以创建一个别名目标，该目标允许引用在只读上下文中设置目标。

为了创建别名目标，可以运行：

[source,cmake]
----
add_library(sublibrary2)
add_library(sub::lib2 ALIAS sublibrary2)
----

可通过如下方式引用别名：
[source,cmake]
----
target_link_libraries(subbinary
    sub::lib2
)
----

## 子项目的包含目录

从cmake v3开始，当从子项目中添加库时，不需要在包含目录中添加项目的包含目录。

这是由创建库时`target_include_directories()`命令所使用的作用域控制的。在本示例中，subbinary的可执行文件链接了两个库：sublibrary1和sublibrary2。这将会同时自动包含 `${sublibrary1_SOURCE_DIR}/inc` 和 `${sublibrary2_SOURCE_DIR}/inc` 两个文件夹。这是由于这两个库的`target_include_directories()`作用域为 +PUBLIC+ 和 +INTERFACE+ 。

# 构建示例

[source,bash]
----
$ mkdir build

$ cd build/

$ cmake ..
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/matrim/workspace/cmake-examples/02-sub-projects/A-basic/build

$ make
Scanning dependencies of target sublibrary1
[ 50%] Building CXX object sublibrary1/CMakeFiles/sublibrary1.dir/src/sublib1.cpp.o
Linking CXX static library libsublibrary1.a
[ 50%] Built target sublibrary1
Scanning dependencies of target subbinary
[100%] Building CXX object subbinary/CMakeFiles/subbinary.dir/main.cpp.o
Linking CXX executable subbinary
[100%] Built target subbinary

----
